### ISSUE TITLE
Crash upon joining server

### ISSUE THREAD

**Issue by scribblemaniac** [scribblemaniac/AwakenDreams#4]
Affected program: Awaken Dreams Client v0.4

Description:
Crash occurs during single and multi player. Reinstalling the mod does not correct the issue. Crash report follows:

```
---- Minecraft Crash Report ----
// You're mean.

Time: 22/03/16 1:22 AM
Description: Ticking screen

java.lang.IndexOutOfBoundsException
    at java.nio.Buffer.checkIndex(Buffer.java:540)
    at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
    at bls.a(RenderGlobal.java:435)
    at bls.a(RenderGlobal.java:377)
    at azd.a(Minecraft.java:2252)
    at azd.a(Minecraft.java:2197)
    at biv.a(NetHandlerPlayClient.java:287)
    at gu.a(S01PacketJoinGame.java:79)
    at gu.a(S01PacketJoinGame.java:127)
    at ef.a(NetworkManager.java:236)
    at bbe.c(GuiConnecting.java:102)
    at azd.o(Minecraft.java:1708)
    at azd.ad(Minecraft.java:1000)
    at azd.e(Minecraft.java:915)
    at net.minecraft.client.main.Main.main(Main.java:109)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at java.nio.Buffer.checkIndex(Buffer.java:540)
    at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
    at bls.a(RenderGlobal.java:435)
    at bls.a(RenderGlobal.java:377)
    at azd.a(Minecraft.java:2252)
    at azd.a(Minecraft.java:2197)
    at biv.a(NetHandlerPlayClient.java:287)
    at gu.a(S01PacketJoinGame.java:79)
    at gu.a(S01PacketJoinGame.java:127)
    at ef.a(NetworkManager.java:236)
    at bbe.c(GuiConnecting.java:102)

-- Affected screen --
Details:
    Screen name: bbe

-- Affected level --
Details:
    Level name: MpServer
    All players: 0 total; []
    Chunk stats: MultiplayerChunkCache: 0, 0
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 0 total; []
    Retry entities: 0 total; []
    Server brand: ~~ERROR~~ NullPointerException: null
    Server type: Non-integrated multiplayer server
Stacktrace:
    at biz.a(WorldClient.java:401)
    at azd.b(Minecraft.java:2592)
    at azd.e(Minecraft.java:936)
    at net.minecraft.client.main.Main.main(Main.java:109)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Mac OS X (x86_64) version 10.11.4
    Java Version: 1.8.0_74, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 147529928 bytes (140 MB) / 255066112 bytes (243 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 18497 (1035832 bytes; 0 MB) allocated, 18497 (1035832 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Launched Version: AD0.4
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 6750M OpenGL Engine GL version 2.1 ATI-1.42.6, ATI Technologies Inc.
    Is Modded: Definitely; Client brand changed to 'awakendreams'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: Canadian English (CA)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
```

**Comment by scribblemaniac** [comment]
Solution has been found by doing the following:
1. Start up vanilla Minecraft (tested with v1.9)
2. Navigate to Options... > Video Settings...
3. Set render distance to 14 chunks (other distances < 20 may work)
4. Close Minecraft completely.

Following these steps should correct the issue temporarily. This issue will be closed when it can be confirmed that v0.5 works for all render distances.
